/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.sample.stackoverflowwebsocket;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.concurrent.atomic.AtomicLong;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author dcaprani
 */
public class LoadTestGUI extends javax.swing.JFrame {

    /**
     * Creates new form LoadTestGUI
     */
    private int port;
    private int clients;
    private int messages;
    private int idleTime;
    private String host;
    private int connections;
    private long conxTime;
    private long msgsTX;
    private long msgsRX;
    private long msgsRXTime;
    private ArrayList<TestResult> resArr = new ArrayList<>();
    
    private ChatBot myChatBot;
    public LoadTestGUI() {
        initComponents();
        hostJTextField.setText("localhost");
        portNoJTextField.setText("8081");
        NoOfClientsJTextField.setText("500");
        msgsPerClientTextField.setText("50");
        idleTimeJTextField.setText("15000");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TitleJLabel = new javax.swing.JLabel();
        portNoJLabel = new javax.swing.JLabel();
        portNoJTextField = new javax.swing.JTextField();
        NoClientsJLabel = new javax.swing.JLabel();
        NoOfClientsJTextField = new javax.swing.JTextField();
        msgsPerClientTextField = new javax.swing.JTextField();
        msgsPerClientJLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        idleTimeJTextField = new javax.swing.JTextField();
        outputJPanel = new javax.swing.JPanel();
        clientsJlbl = new javax.swing.JLabel();
        conxjLbl = new javax.swing.JLabel();
        timeJLbl = new javax.swing.JLabel();
        clientsOutputJLbl = new javax.swing.JLabel();
        conxOutputJLbl = new javax.swing.JLabel();
        conxTimeOutputJLbl = new javax.swing.JLabel();
        msgTXJLbl = new javax.swing.JLabel();
        msgsRXJLbl = new javax.swing.JLabel();
        msgTXOutputJLbl = new javax.swing.JLabel();
        msgsRXOutputJLbl = new javax.swing.JLabel();
        msgsTimeOutputJLbl = new javax.swing.JLabel();
        engageJButton = new javax.swing.JButton();
        hostJLable = new javax.swing.JLabel();
        hostJTextField = new javax.swing.JTextField();
        printToFileJButton = new javax.swing.JButton();
        srvrNameJLabel = new javax.swing.JLabel();
        srvrNameJTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TitleJLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TitleJLabel.setText("WebSocket Chat Application Load Tester");

        portNoJLabel.setText("Port No.:");

        NoClientsJLabel.setText("Number of Clients to connect");

        msgsPerClientJLabel.setText("Number of Messages per Client");

        jLabel1.setText("Idle time");

        outputJPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), new java.awt.Color(102, 102, 102)));

        clientsJlbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        clientsJlbl.setText("Clients");

        conxjLbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        conxjLbl.setText("Connections");

        timeJLbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        timeJLbl.setText("Time in ms");

        msgTXJLbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        msgTXJLbl.setText("Messages TX");

        msgsRXJLbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        msgsRXJLbl.setText("Messages RX");

        javax.swing.GroupLayout outputJPanelLayout = new javax.swing.GroupLayout(outputJPanel);
        outputJPanel.setLayout(outputJPanelLayout);
        outputJPanelLayout.setHorizontalGroup(
            outputJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(outputJPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(outputJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(msgTXOutputJLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(clientsJlbl)
                    .addComponent(clientsOutputJLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(msgTXJLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(outputJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(outputJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(conxjLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(conxOutputJLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(outputJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(msgsRXOutputJLbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(msgsRXJLbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(67, 67, 67)
                .addGroup(outputJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(timeJLbl)
                    .addComponent(conxTimeOutputJLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(msgsTimeOutputJLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE))
                .addGap(33, 33, 33))
        );
        outputJPanelLayout.setVerticalGroup(
            outputJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(outputJPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(outputJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clientsJlbl, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(conxjLbl, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(timeJLbl, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(outputJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clientsOutputJLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(conxOutputJLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(conxTimeOutputJLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(outputJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(msgTXJLbl, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(msgsRXJLbl, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(outputJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(msgTXOutputJLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(msgsRXOutputJLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(msgsTimeOutputJLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        engageJButton.setText("Engage");
        engageJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                engageJButtonActionPerformed(evt);
            }
        });

        hostJLable.setText("Host :");

        printToFileJButton.setText("Print Results To File");
        printToFileJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printToFileJButtonActionPerformed(evt);
            }
        });

        srvrNameJLabel.setText("Server Under Test:");

        srvrNameJTextField.setToolTipText("Enter Server Name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(printToFileJButton)
                .addGap(19, 19, 19))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(outputJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(277, 277, 277)
                        .addComponent(idleTimeJTextField)
                        .addGap(1, 1, 1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(msgsPerClientJLabel)
                        .addGap(156, 156, 156)
                        .addComponent(msgsPerClientTextField))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(NoClientsJLabel)
                        .addGap(166, 166, 166)
                        .addComponent(NoOfClientsJTextField))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(portNoJLabel)
                            .addComponent(hostJLable))
                        .addGap(261, 261, 261)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(portNoJTextField)
                            .addComponent(hostJTextField))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(srvrNameJLabel)
                        .addGap(213, 213, 213)
                        .addComponent(srvrNameJTextField))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(91, 91, 91)
                                .addComponent(TitleJLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(178, 178, 178)
                                .addComponent(engageJButton)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TitleJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(srvrNameJLabel)
                    .addComponent(srvrNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hostJLable)
                    .addComponent(hostJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(portNoJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(portNoJLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NoOfClientsJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NoClientsJLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(msgsPerClientTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(msgsPerClientJLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idleTimeJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(engageJButton)
                .addGap(18, 18, 18)
                .addComponent(outputJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(printToFileJButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        
    private void engageJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_engageJButtonActionPerformed
        // TODO add your handling code here:
        // set output labels to empty strings
        myChatBot = null;
        connections = 0;
        msgsTX = 0;
        msgsRX = 0;
        conxTime = 0;
        msgsRXTime = 0;
        //myChatBot.
        conxOutputJLbl.setText("");
        conxTimeOutputJLbl.setText("");
        msgTXOutputJLbl.setText("");
        msgsRXOutputJLbl.setText("");
        msgsTimeOutputJLbl.setText("");
        // Capture input from user
        port = Integer.parseInt(portNoJTextField.getText());
        host = hostJTextField.getText();
        clients = Integer.parseInt(NoOfClientsJTextField.getText());
        clientsOutputJLbl.setText(NoOfClientsJTextField.getText());
        messages = Integer.parseInt(msgsPerClientTextField.getText());
        idleTime = Integer.parseInt(idleTimeJTextField.getText());
        try {
            // Create instance of ChatBot
            myChatBot = new ChatBot(clients, messages, idleTime);
            myChatBot.compute(host, port);
        } catch (Exception ex) {
            Logger.getLogger(LoadTestGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        // gather data for output
        connections = myChatBot.getMembersSize();
        msgsTX = myChatBot.getSent();
        msgsRX = myChatBot.getReceived();
        conxTime = myChatBot.getConxTime();
        msgsRXTime = myChatBot.getRXTime();
        String serverName = srvrNameJTextField.getText();
        LocalDateTime date = LocalDateTime.now();
       
        // set relevant output labels
        conxOutputJLbl.setText(Integer.toString(connections));
        conxTimeOutputJLbl.setText(Long.toString(conxTime));
        msgTXOutputJLbl.setText(Long.toString(msgsTX));
        msgsRXOutputJLbl.setText(Long.toString(msgsRX));
        msgsTimeOutputJLbl.setText(Long.toString(msgsRXTime));
        // reset values
        TestResult tRes = new TestResult(serverName, date, clients, connections, conxTime, msgsTX, msgsRX, msgsRXTime);
        resArr.add(tRes);

        myChatBot.resetValues();
    }//GEN-LAST:event_engageJButtonActionPerformed

    private void printToFileJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printToFileJButtonActionPerformed
         
        try{
            
            File f = new File("Results.txt");
            FileWriter fw = new FileWriter(f, true);
            BufferedWriter bWriter = new BufferedWriter(fw);
            PrintWriter pWriter = new PrintWriter(bWriter);
            //pWriter.println(serverName + "\t" + date + "\t" + clients + "\t" + connections + "\t" + (connections/clients) + "\t" + conxTime + "\t" + msgsTX + "\t" + msgsRX + "\t" + (msgsRX/(msgsTX*clients)) + "\t" + msgsRXTime);
            pWriter.println("Server Name\tTest Date/Time\tClients\tClients Cnctd\tCNX %\tCNX Time\tMsgs TX\tMsgs RX\tRX %\tTX/RX Time");
 
            for(TestResult tr: resArr){
               pWriter.println(tr.printResult());
            }
            
            bWriter.close();
        }catch(IOException e){
            System.out.println(e.toString() + "Error writing to file");
        }
    }//GEN-LAST:event_printToFileJButtonActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoadTestGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoadTestGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoadTestGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoadTestGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        final LoadTestGUI ltg = new LoadTestGUI();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoadTestGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NoClientsJLabel;
    private javax.swing.JTextField NoOfClientsJTextField;
    private javax.swing.JLabel TitleJLabel;
    private javax.swing.JLabel clientsJlbl;
    private javax.swing.JLabel clientsOutputJLbl;
    private javax.swing.JLabel conxOutputJLbl;
    private javax.swing.JLabel conxTimeOutputJLbl;
    private javax.swing.JLabel conxjLbl;
    private javax.swing.JButton engageJButton;
    private javax.swing.JLabel hostJLable;
    private javax.swing.JTextField hostJTextField;
    private javax.swing.JTextField idleTimeJTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel msgTXJLbl;
    private javax.swing.JLabel msgTXOutputJLbl;
    private javax.swing.JLabel msgsPerClientJLabel;
    private javax.swing.JTextField msgsPerClientTextField;
    private javax.swing.JLabel msgsRXJLbl;
    private javax.swing.JLabel msgsRXOutputJLbl;
    private javax.swing.JLabel msgsTimeOutputJLbl;
    private javax.swing.JPanel outputJPanel;
    private javax.swing.JLabel portNoJLabel;
    private javax.swing.JTextField portNoJTextField;
    private javax.swing.JButton printToFileJButton;
    private javax.swing.JLabel srvrNameJLabel;
    private javax.swing.JTextField srvrNameJTextField;
    private javax.swing.JLabel timeJLbl;
    // End of variables declaration//GEN-END:variables
}
